name: Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npx pnpm i --frozen-lockfile
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test --if-present
